
spring:
  application:
    name: bp
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/bp
    username: bp
    password: bp
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
